name: Docker CI - DEV

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Login no Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p  ${{ secrets.DOCKER_PASSWORD }}

      - name: Build imagem DEV
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          docker tag $(docker build -q .) $DOCKER_USER/hack-n-tap:dev

      - name: Publish imagem DEV
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: docker push $DOCKER_USER/hack-n-tap:dev
